### ISSUE TITLE
pip install ... IOError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by IlyaParachuter** [thiagof/py-poloniex#1]
censored:~$ pip --no-cache-dir install py-poloniex
Collecting py-poloniex
  Downloading py-poloniex-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kwLagj/py-poloniex/setup.py", line 7, in <module>
        long_description=open('README.md').read().strip(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kwLagj/py-poloniex/
censored:~$

**Comment by macedd** [comment]
Please checkout, fixed in version 0.4.1
