### ISSUE TITLE
Convert strings to bytearray in API

### ISSUE THREAD

**Issue by hannes-michael** [thiagof/py-poloniex#4]
I just tried the api connection and noticed that you need to convert self.Secret, and post_data to a bytearray.

My tries with
`bytes(self.Secret, "ascii")`
don't want to work.
```
sign = hmac.new(self.Secret, post_data, hashlib.sha512).hexdigest()
            headers = {
                'Sign': sign,
                'Key': self.APIKey
            }
            
ret = urlopen(Request('https://poloniex.com/tradingApi', post_data, headers))
```

**Comment by macedd** [comment]
Are you using an old API Key? For some reason the keys created long ago fail to sign requests.
